openapi: 3.0.3
info:
  title: Mint2 Common
  version: 1.0.0

components:
  schemas:
    ErrorDto:
      type: object
      required:
        - message
        - statusCode
      properties:
        message:
          type: string
        statusCode:
          type: integer